apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: configmapmanagers.blacksyrius.ci.com
spec:
  group: blacksyrius.ci.com
  names:
    kind: ConfigMapManager
    listKind: ConfigMapManagerList
    plural: configmapmanagers
    singular: configmapmanager
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                configMaps:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      updates:
                        type: array
                        items:
                          type: object
                          properties:
                            key:
                              type: string
                            newValue:
                              type: string
