apiVersion: blacksyrius.ci.com/v1
kind: ConfigMapManager
metadata:
  name: my-configmap-update
  namespace: default
spec:
  configMaps:
    - name: example-config
      updates:
        - key: LOG_LEVEL
          newValue: "info"
        - key: DB_HOST
          newValue: "mysql.example-new-2.com"
    - name: another-config
      updates:
        - key: API_URL
          newValue: "https://api.example.com"
        - key: RETRY_COUNT
          newValue: "5"
