apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-app-1
  namespace: app-1
spec:
  selector:
    matchLabels:
      app: nginx-deployment-app-1
  template:
    metadata:
      labels:
        app: nginx-deployment-app-1
    spec:
      containers:
      - name: nginx-deployment-app-1
        image: nginx:1.14.2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: example-config
        - configMapRef:
            name: another-config
